(function initUiCopy(namespace) {
  "use strict";

  const tables = {
    tr: {
      appName: "LearnGodot",
      appTagline: "Godot + GDScript öğrenme alanı",
      productPositioning: "Godot'u, GDScript'in temelini ve oyun geliştirme kavramlarını sıfırdan, sırayla ve bağlantılı biçimde öğren.",
      saved: "İlerlemen bu cihazda otomatik kaydedilir.",
      nav: {
        dashboard: "Dashboard",
        learn: "Öğren",
        terms: "Terimler",
        quiz: "Quiz",
        review: "Tekrar",
        favorites: "Favoriler",
      },
      routeTitles: {
        lesson: "Ders",
        topic: "Konu",
        term: "Terim",
        notFound: "Sayfa bulunamadı",
      },
      actions: {
        startLesson: "Derse Başla",
        continueLesson: "Kaldığın Yerden Devam Et",
        finishLesson: "Dersi Bitir",
        repeatLesson: "Dersi Tekrar Et",
        start: "Başla",
        continue: "Devam Et",
        previousTopic: "Önceki Konu",
        nextTopic: "Sonraki Konu",
        completeTopic: "Konuyu tamamla",
        completeLesson: "Dersi Tamamla",
        undoLesson: "Tamamlamayı geri al",
        openLesson: "Dersi aç",
        continueCourse: "Derse devam et",
        repeat: "Tekrar et",
        search: "Terim ara",
        copy: "Kopyala",
        copied: "Kopyalandı",
        revealAnswer: "Cevabı göster",
        clearFilters: "Filtreleri temizle",
        browseTerms: "Terimlere göz at",
        goToReview: "Tekrara git",
        browseGlossary: "Sözlüğe göz at",
        discoverTerms: "Terimleri keşfet",
        returnDashboard: "Dashboard'a dön",
        continueLearning: "Öğrenmeye devam et",
        closeExplanation: "Açıklamayı kapat",
      },
      aria: {
        mainNavigation: "Ana navigasyon",
        openMenu: "Menüyü aç",
        closeMenu: "Menüyü kapat",
        changeTheme: "Temayı değiştir",
        contentPath: "İçerik yolu",
        lessonTopics: "Ders konuları arasında gezinme",
        coreTerms: "Temel terimler arasında gezinme",
        termFilters: "Terim filtreleri",
        letterFilter: "Harf filtresi",
        quizLesson: "Quiz dersi",
        openLesson: (title) => `${title} dersini aç`,
        explainConcept: (title) => `${title} kavramını açıkla`,
        startTopic: (title) => `${title} konusuna başla`,
      },
      status: {
        progress: "İlerleme",
        localProgress: "Yerel ilerleme",
        core: "Temel",
        recognize: "Tanı",
        learned: "Öğrenildi",
        completed: "Tamamlandı",
        completedLower: "tamamlandı",
        nextLesson: "Sıradaki ders",
        nextTopic: "Sıradaki konu",
        noPrerequisite: "Ön bilgi gerektirmez",
        favorite: "Favori",
        favorited: "Favoride",
        inReview: "Tekrarda",
        general: "Genel",
        lessonsCompleted: (done, total) => `${done} / ${total} ders tamamlandı`,
        termsLearned: (done, total) => `${done} / ${total} terim öğrenildi`,
        percentCompleted: (value) => `%${value} tamamlandı`,
        topicsCompleted: (done, total) => `${done} / ${total} konu tamamlandı`,
        coreTermsLearned: "temel terim öğrenildi",
        minutesShort: (value) => `${value} dk`,
        minutesLong: (value) => `${value} dakika`,
        coreConcepts: (value) => `${value} temel kavram`,
        coreTerms: (value) => `${value} temel terim`,
        topics: (value) => `${value} konu`,
        lessonNumber: (value) => `Ders ${String(value).padStart(2, "0")}`,
        topicPosition: (value, total) => `Konu ${value} / ${total}`,
        reviewTerms: (value) => `${value} terim tekrar listende`,
        termCount: (value) => `${value} terim`,
        relatedTerms: (value) => `${value} terim`,
        lessonProgressLabel: (title) => `${title} ilerlemesi`,
        coreConcept: "Temel kavram",
      },
      terms: {
        openDetails: "detayını aç",
        addFavorite: "Favorilere ekle",
        removeFavorite: "Favorilerden çıkar",
        viewDetails: "Detayı gör",
        connections: "Bağlantılar",
        related: "İlgili terimler",
        previousCore: "Önceki temel terim",
        nextCore: "Sonraki temel terim",
      },
      search: {
        placeholder: "Terim, alias veya tanım ara…",
        glossaryPlaceholder: "Terimlerde ara…",
        label: "Terim ara",
        prompt: "Aramaya başlamak için bir terim yaz.",
        intro: "Tüm terimler içinde ada, alias'a veya tanıma göre ara.",
        empty: "Bu aramayla eşleşen bir terim yok.",
        shortcut: "Ctrl / ⌘ K",
        navigate: "gezin",
        open: "aç",
        results: (count) => `${count} sonuç`,
      },
      dashboard: {
        eyebrow: "Türkçe başlangıç rotası",
        title: "Godot'u Türkçe Öğren",
        roadmap: "Yol haritası",
        overview: "Derslere genel bakış",
        viewAll: "Tümünü gör",
        recall: "Hatırlama",
        reviewQueue: "Tekrar kuyruğu",
        queueClean: "Kuyruk temiz",
        queueCleanDescription: "Zorlandığın terimleri veya quiz sorularını tekrar için işaretleyebilirsin.",
        startReview: "Tekrara başla",
        waitingReview: "tekrar öğesi seni bekliyor",
        lessonProgress: "Ders ilerlemesi",
        coreTerms: "Temel terimler",
        first50: "İlk 50 rotası",
        completeEyebrow: "Kurs tamamlandı",
        completeTitle: "Başlangıç yolunu tamamladın",
        completeDescription: "14 dersin tamamlandı. İstersen zorlandığın kavramları tekrar edebilir veya sözlüğe göz atabilirsin.",
      },
      learn: {
        eyebrow: "Başlangıç kursu",
        title: "Godot'u adım adım öğren",
        description: "Her bölüm bir öncekinin üzerine kurulur. Sıradaki dersi açıp kaldığın yerden devam et.",
        courseProgress: "Kurs ilerlemesi",
      },
      lesson: {
        goal: "Bu dersteki hedefin",
        termsProgress: "Ders terimleri",
        activeLearning: "Aktif öğrenme",
        coreTerms: "Temel terimler",
        coreDescription: "Tanımın yanında bağlamı ve hatırlama ipucunu da çalış.",
        quickRecognition: "Hızlı tanıma",
        recognizeTitle: "Duyunca yabancı gelmesin",
        recognizeDescription: "Şimdilik bu terimleri kategorisi ve kısa anlamıyla tanıman yeterli.",
        completedTitle: "Bu dersi tamamladın",
        finishTitle: "Dersi bitirdin mi?",
        completedDescription: "İstersen terimleri yeniden gözden geçirebilirsin.",
        finishDescription: "Ders durumu ile tek tek öğrenilen terimler birbirinden bağımsız kaydedilir.",
        previous: "Önceki ders",
        next: "Sonraki ders",
        upNext: "Sırada",
        goToQuizzes: "Quizlere geç",
      },
      guided: {
        lesson: "Guided ders",
        afterLesson: "Bu dersten sonra",
        oneScreen: "Her konu tek ekranda",
        inlineHelp: "Bilinmeyen terimler sayfadan ayrılmadan açıklanır",
        oneDirection: "Her adımda tek bir sonraki yön vardır",
        route: "Ders rotası",
        routeTitle: "Adım adım büyük resmi kur",
        routeDescription: "Konuları sırayla çalış. Bir sonraki konuya geçtiğinde bulunduğun konu ilerlemene kaydedilir.",
        recognizeEyebrow: "Ders boyunca",
        recognizeTitle: "“Bunu duyarsan tanı” kutuları",
        lessonPlan: "Ders planı",
        prerequisite: "Bu konudan önce bilmen iyi olur",
        bridge: "Buraya nasıl geldik?",
        fast: "30 saniyede",
        model: "Basit zihinsel model",
        why: "Neden buna ihtiyacımız var?",
        godotContext: "Godot'ta nerede görürüm?",
        example: "Örnek",
        quickTerms: "Bilmediğim terimler",
        quickTermsDescription: "Bu konuyu anlamak için gerekli teknik kavramları burada kısa açıklamalarıyla açabilirsin.",
        recognize: "Bunu duyarsan tanı",
        mistake: "Yaygın hata",
        check: "Kendini kontrol et",
        answerPrompt: "Tek cümleyle yanıtla",
        shortAnswer: "Kısa cevap",
        enoughForNow: "Şimdilik bunu bilmen yeterli",
        summary: "Ders özeti",
        defaultSummaryTitle: "Bu derste parçalar nasıl birleşiyor?",
        recognizeDescription: (count) => `${count} ek terimi uzun derslere çevirmeden, bağlantılı olduğu konunun yanında kısa anlamı ve ayrımıyla göreceksin.`,
        cardTag: "Tanı",
        cardBrief: "Kısaca",
        cardConnection: "Bu konuyla bağlantısı",
        cardWhy: "Neden burada?",
        cardDistinction: "Karıştırma",
      },
      glossary: {
        eyebrow: "Hızlı referans",
        title: "Terimler A–Z",
        allLevels: "Tüm seviyeler",
        allCategories: "Tüm kategoriler",
        allLetters: "Tümü",
        filtered: "Filtrelenmiş sonuçlar",
        alphabetical: "Alfabetik sıralama",
        noResults: "Sonuç bulunamadı",
        description: (count) => `${count} Godot, GDScript ve oyun geliştirme terimi.`,
      },
      termDetail: {
        core: "Temel terim",
        recognize: "Tanıma terimi",
        aliases: "Diğer adları",
        definition: "Tanım",
        context: "Bağlam",
        whereHeard: "Nerede duyarsın?",
        memory: "Akılda kalsın",
        codeExample: "Kod örneği",
        studyStatus: "Çalışma durumu",
        markLearned: "Öğrendim olarak işaretle",
        savedLearned: "İlerlemene eklendi",
        saveProgress: "İlerlemene kaydet",
        inContent: "Bu içerikte",
        level: "Seviye",
        lesson: "Ders",
        relation: "İlişki",
      },
      review: {
        eyebrow: "Odaklı tekrar",
        title: "Zorlandıklarına geri dön.",
        description: "İşaretlediğin terimler ve yeniden çözmek istediğin sorular burada toplanır.",
        terms: "Terimler",
        questions: "Sorular",
        thinkAgain: "Yeniden düşün",
        emptyTitle: "Tekrar listesi boş",
        emptyDescription: "Tekrar listen şu an boş.",
      },
      favorites: {
        eyebrow: "Kişisel koleksiyon",
        title: "Favori terimlerin",
        description: "Sık döndüğün kavramları tek yerde tut.",
        emptyTitle: "Koleksiyonun boş",
        emptyDescription: "Henüz favori terimin yok.",
      },
      quiz: {
        eyebrow: "Açık hatırlama",
        title: "Kendini test et.",
        description: "Önce cevabı zihninden kur, sonra kaynak cevabı aç ve kendini değerlendir.",
        allLessons: "Tüm dersler",
        answerYourself: "Kendi cümlenle yanıtla",
        sourceAnswer: "Kaynak cevap",
        rating: "Nasıl geçti?",
        remembered: "Hatırladım",
        evaluated: "değerlendirildi",
        progress: "Quiz ilerlemesi",
      },
      messages: {
        favoriteAdded: "Favorilere eklendi.",
        favoriteRemoved: "Favorilerden çıkarıldı.",
        reviewAdded: "Tekrar listesine eklendi.",
        reviewRemoved: "Tekrar listesinden çıkarıldı.",
        learnedAdded: "Terim öğrenildi olarak işaretlendi.",
        learnedRemoved: "Öğrenildi işareti kaldırıldı.",
        lessonCompleted: "Ders tamamlandı. Harika iş.",
        lessonUncompleted: "Ders tamamlanmadı olarak işaretlendi.",
        finishRemaining: "Dersi tamamlamadan önce kalan konuyu çalış.",
        answerSaved: "Yanıt kaydedildi.",
        questionReviewAdded: "Soru tekrar listene eklendi.",
        copyFailed: "Kod kopyalanamadı.",
        numberedLessonCompleted: (number) => `${number}. ders tamamlandı.`,
      },
      errors: {
        copyUnsupported: "Kopyalama desteklenmiyor.",
        startupTitle: "Uygulama başlatılamadı.",
        startupDescription: "İçerik dosyalarının index.html ile birlikte bulunduğundan emin ol.",
        notFoundDescription: "Aradığın sayfa burada değil.",
      },
    },
  };

  window.GODOT_UI_COPY = tables;
  namespace.COPY = tables[namespace.locale?.contentLocale ?? "tr"] ?? tables.tr;
})(window.GodotApp = window.GodotApp || {});
